//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int SchoolClass_Id { get; set; }
    
        public virtual School School { get; set; }
    }
}
